# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.uv.symptoms
canonical: http://hl7.org/fhir/uv/symptoms
name: Symptoms Data Standards
title: FHIR R4 Symptoms Implementation Guide
description: A guide that details how to capture and exchange Symptoms data in FHIR
status: active # draft | active | retired | unknown
version: 0.1.0
fhirVersion: 6.0.0-ballot3 
copyrightYear: 2025+
releaseLabel: ci-build
license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001 "World" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: HL7 International / Clinical Interoperability Council
  url: http://www.hl7.org/Special/committees/cic
extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 1
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: cic

dependencies:

parameters:
  path-resource: input/resources/graphdefinition
  additional-resource: input/resources/graphdefinition/StructureDefinition-GraphDefinition.xml
  special-url-base: http://hl7.org/fhir
  
pages:
  index.md:
    title: IG Home
  changes.md:
    title: Change Log
  background.md:
    title: Background
  exchange.md:
    exchange: Exchange

menu:
  Home: index.html
  Background:
    Reading this IG: background.html
  Specification:
    Exchange Patterns: exchange.html
  FHIR Artifacts:
    Artifacts: artifacts.html
  Support:
    Discussion Forum: https://chat.fhir.org/#channels/501058/Symptoms.20on.20FHIR
#    Project Dashboard: 
#    Propose a Change: 
  Change Log: changes.html
